#
# Autogenerated by Thrift Compiler (0.20.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def createResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        pass

    def dropResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        pass

    def recoverResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        pass

    def upgradeResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def createResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        self.send_createResp(state, aid)

    def send_createResp(self, state, aid):
        self._oprot.writeMessageBegin('createResp', TMessageType.ONEWAY, self._seqid)
        args = createResp_args()
        args.state = state
        args.aid = aid
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def dropResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        self.send_dropResp(state, aid)

    def send_dropResp(self, state, aid):
        self._oprot.writeMessageBegin('dropResp', TMessageType.ONEWAY, self._seqid)
        args = dropResp_args()
        args.state = state
        args.aid = aid
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recoverResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        self.send_recoverResp(state, aid)

    def send_recoverResp(self, state, aid):
        self._oprot.writeMessageBegin('recoverResp', TMessageType.ONEWAY, self._seqid)
        args = recoverResp_args()
        args.state = state
        args.aid = aid
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def upgradeResp(self, state, aid):
        """
        Parameters:
         - state
         - aid

        """
        self.send_upgradeResp(state, aid)

    def send_upgradeResp(self, state, aid):
        self._oprot.writeMessageBegin('upgradeResp', TMessageType.ONEWAY, self._seqid)
        args = upgradeResp_args()
        args.state = state
        args.aid = aid
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["createResp"] = Processor.process_createResp
        self._processMap["dropResp"] = Processor.process_dropResp
        self._processMap["recoverResp"] = Processor.process_recoverResp
        self._processMap["upgradeResp"] = Processor.process_upgradeResp
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_createResp(self, seqid, iprot, oprot):
        args = createResp_args()
        args.read(iprot)
        iprot.readMessageEnd()
        try:
            self._handler.createResp(args.state, args.aid)
        except TTransport.TTransportException:
            raise
        except Exception:
            logging.exception('Exception in oneway handler')

    def process_dropResp(self, seqid, iprot, oprot):
        args = dropResp_args()
        args.read(iprot)
        iprot.readMessageEnd()
        try:
            self._handler.dropResp(args.state, args.aid)
        except TTransport.TTransportException:
            raise
        except Exception:
            logging.exception('Exception in oneway handler')

    def process_recoverResp(self, seqid, iprot, oprot):
        args = recoverResp_args()
        args.read(iprot)
        iprot.readMessageEnd()
        try:
            self._handler.recoverResp(args.state, args.aid)
        except TTransport.TTransportException:
            raise
        except Exception:
            logging.exception('Exception in oneway handler')

    def process_upgradeResp(self, seqid, iprot, oprot):
        args = upgradeResp_args()
        args.read(iprot)
        iprot.readMessageEnd()
        try:
            self._handler.upgradeResp(args.state, args.aid)
        except TTransport.TTransportException:
            raise
        except Exception:
            logging.exception('Exception in oneway handler')

# HELPER FUNCTIONS AND STRUCTURES


class createResp_args(object):
    """
    Attributes:
     - state
     - aid

    """


    def __init__(self, state=None, aid=None,):
        self.state = state
        self.aid = aid

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.state = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.aid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('createResp_args')
        if self.state is not None:
            oprot.writeFieldBegin('state', TType.I32, 1)
            oprot.writeI32(self.state)
            oprot.writeFieldEnd()
        if self.aid is not None:
            oprot.writeFieldBegin('aid', TType.I32, 2)
            oprot.writeI32(self.aid)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(createResp_args)
createResp_args.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'state', None, None, ),  # 1
    (2, TType.I32, 'aid', None, None, ),  # 2
)


class dropResp_args(object):
    """
    Attributes:
     - state
     - aid

    """


    def __init__(self, state=None, aid=None,):
        self.state = state
        self.aid = aid

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.state = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.aid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('dropResp_args')
        if self.state is not None:
            oprot.writeFieldBegin('state', TType.I32, 1)
            oprot.writeI32(self.state)
            oprot.writeFieldEnd()
        if self.aid is not None:
            oprot.writeFieldBegin('aid', TType.I32, 2)
            oprot.writeI32(self.aid)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(dropResp_args)
dropResp_args.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'state', None, None, ),  # 1
    (2, TType.I32, 'aid', None, None, ),  # 2
)


class recoverResp_args(object):
    """
    Attributes:
     - state
     - aid

    """


    def __init__(self, state=None, aid=None,):
        self.state = state
        self.aid = aid

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.state = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.aid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('recoverResp_args')
        if self.state is not None:
            oprot.writeFieldBegin('state', TType.I32, 1)
            oprot.writeI32(self.state)
            oprot.writeFieldEnd()
        if self.aid is not None:
            oprot.writeFieldBegin('aid', TType.I32, 2)
            oprot.writeI32(self.aid)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(recoverResp_args)
recoverResp_args.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'state', None, None, ),  # 1
    (2, TType.I32, 'aid', None, None, ),  # 2
)


class upgradeResp_args(object):
    """
    Attributes:
     - state
     - aid

    """


    def __init__(self, state=None, aid=None,):
        self.state = state
        self.aid = aid

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.state = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.aid = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('upgradeResp_args')
        if self.state is not None:
            oprot.writeFieldBegin('state', TType.I32, 1)
            oprot.writeI32(self.state)
            oprot.writeFieldEnd()
        if self.aid is not None:
            oprot.writeFieldBegin('aid', TType.I32, 2)
            oprot.writeI32(self.aid)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(upgradeResp_args)
upgradeResp_args.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'state', None, None, ),  # 1
    (2, TType.I32, 'aid', None, None, ),  # 2
)
fix_spec(all_structs)
del all_structs
