ZK_HOST = '127.0.0.1'
ZK_PORT = '2181'
ZK_ADDR = f'{ZK_HOST}:{ZK_PORT}'

MASTER_HOST = '127.0.0.1'
MASTER_PORT = '3932'
MASTER_ADDR = f'{MASTER_HOST}:{MASTER_PORT}'

ZK_MASTER = '/master'
ZK_REGION_DIR = '/rs'
ZK_SEPARATOR = ' '

DDB_COPY_NUM = 2
